config/routes.rb
Rails.application.routes.draw do
  root 'pages#one'
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end
  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <ul>
      <span><%=link_to "one", pages_one_path %></span>
      <span><%=link_to "two", pages_two_path %></span>
      <span><%=link_to "three", pages_three_path %></span>
      
    </ul>  
    </div>
  </div>
</nav>
    
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Miguel Liendo</h1>
<p>Lorem ipsum dolor sit</p>

app/views/pages/three.html.erb
<h1>lorem</h1>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae minima inventore illo pariatur commodi similique distinctio quos excepturi temporibus aperiam hic, odit, maxime amet nulla accusamus eligendi quia molestias! Porro.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<%=image_tag 'mliendo.png' %>